import type { NextPage } from 'next';
import Head from 'next/head';
import { trpc } from '@utils/trpc';

import Card from '@components/Card/Card';

const Home: NextPage = () => {
	const posts = trpc.useQuery(['post.all']);

	return (
		<>
			<Head>
				<title>Prjawal D Ankit</title>
				<meta
					name="description"
					content="Generated by create-t3-app"
				/>
				<link
					rel="icon"
					href="/favicon.ico"
				/>
			</Head>

			<main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
				<h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700">
					<span className="text-purple-300">Prajwal</span>
				</h1>
				<p className="text-2xl text-gray-700">Languages I'm experienced with:</p>
				<div className="grid gap-3 pt-3 mt-3 text-center md:grid-cols-2 lg:w-2/3">
					{posts.isLoading && <p className="text-red-800 text-5xl">Loading</p>}
					{posts.data?.map((post) => (
						<Card
							key={post.id}
							title={post.title}
							description={post.description}
						/>
					))}
				</div>
			</main>
		</>
	);
};

export default Home;
