import type { NextPage } from 'next';
import Head from 'next/head';
import { styles } from 'styles/styles';
import { trpc } from 'utils/trpc';

import Card from 'Components/Card/Card';

const Home: NextPage = () => {
	const someValue = trpc.useQuery(['post.all']);
	// const hello = trpc.useQuery(["example.hello", { text: "World" }]);
	console.log({ someValue });

	return (
		<>
			<Head>
				<title>Prjawal D Ankit</title>
				<meta
					name="description"
					content="Generated by create-t3-app"
				/>
				<link
					rel="icon"
					href="/favicon.ico"
				/>
			</Head>

			<main className={styles.appContainer}>
				<h1 className={styles.title}>
					<span className={styles.purple}>Prajwal</span>
				</h1>
				<p className={styles.body}>Languages I'm experienced with:</p>
				<div className={styles.grid}>
					<Card
						name="NextJS"
						url="https://nextjs.org/"
					/>
					<Card
						name="React"
						url="#"
					/>
					<Card
						name="Redux, Redux/toolkit"
						url="#"
					/>
					<Card
						name="TypeScript"
						url="https://www.typescriptlang.org/"
					/>
					<Card
						name="TailwindCSS"
						url="https://tailwindcss.com/"
					/>
					<Card
						name="tRPC"
						url="https://trpc.io/"
					/>
				</div>
				{/* <div className={styles.queryResponse}>{hello.data ? <p>{hello.data.greeting}</p> : <p>Loading..</p>}</div> */}
			</main>
		</>
	);
};

export default Home;
